### ISSUE TITLE
join request

### ISSUE THREAD

**Issue by ipshtkleegetolb73** [linehackerschool/linehackerschool.github.io#1]
参加希望の方はこちらにメッセージの書き込みをお願いします

メールを送信した方にはリアクションをつけます

**Comment by nakasyou** [comment]
やりたいです。
一応HTML,JS,CSSかけます

**Comment by k0011m** [comment]
僕もやりたい

**Comment by ipshtkleegetolb73** [comment]
メールを送信します

**Comment by ghost** [comment]
お願いします、
参加希望です。
きしやまです

**Comment by Futaba411** [comment]
(/・ω・)/にゃー!

**Comment by k0011m** [comment]
(・∀・)

2022年8月22日(月) 1:06 Futaba ***@***.***>:

**Comment by tanakahaninja** [comment]
参加したいです。まだまだ未熟ですがこれから学んでいくつもりです。

**Comment by tama-2022** [comment]
手伝いたいです。ネットワークとクラウドを少々扱えます。

**Comment by ipshtkleegetolb73** [comment]
@k0011m 
@Kishiyama-cat 
@tanakahaninja 
@tama-2022 
メールをご確認ください。
送信されたメールからチームに参加してください。

**Comment by ware255** [comment]
ノ
ノ

**Comment by ipshtkleegetolb73** [comment]
一旦クローズします。
以降は権限を持っているメンバーに直接連絡を取って下さい。

**Comment by ipshtkleegetolb73** [comment]
一旦クローズします。
以降は権限を持っているメンバーに直接連絡を取って下さい。
